// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0-gEaeYGGjjxyXnn1HM2jESklP36mZIo',
    appId: '1:691596725478:web:2c25aa772da2d904643f27',
    messagingSenderId: '691596725478',
    projectId: 'skavia-113a3',
    authDomain: 'skavia-113a3.firebaseapp.com',
    storageBucket: 'skavia-113a3.firebasestorage.app',
    measurementId: 'G-KZBTTX9Z8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xzpdzXMTWFSDrzpTD4lxE6l8ZdV1bMQ',
    appId: '1:691596725478:android:4e5aade91f773636643f27',
    messagingSenderId: '691596725478',
    projectId: 'skavia-113a3',
    storageBucket: 'skavia-113a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ6yy6dAyWnBo4quohdnPNSRcTwqVZGQI',
    appId: '1:691596725478:ios:e5a49a866d7411da643f27',
    messagingSenderId: '691596725478',
    projectId: 'skavia-113a3',
    storageBucket: 'skavia-113a3.firebasestorage.app',
    iosBundleId: 'com.example.skavia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ6yy6dAyWnBo4quohdnPNSRcTwqVZGQI',
    appId: '1:691596725478:ios:e5a49a866d7411da643f27',
    messagingSenderId: '691596725478',
    projectId: 'skavia-113a3',
    storageBucket: 'skavia-113a3.firebasestorage.app',
    iosBundleId: 'com.example.skavia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0-gEaeYGGjjxyXnn1HM2jESklP36mZIo',
    appId: '1:691596725478:web:ad597d331e0cb6a1643f27',
    messagingSenderId: '691596725478',
    projectId: 'skavia-113a3',
    authDomain: 'skavia-113a3.firebaseapp.com',
    storageBucket: 'skavia-113a3.firebasestorage.app',
    measurementId: 'G-SYFH3EMJF9',
  );
}
